name: Node.js API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: CarDealership_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend_bd
          npm install

      - name: Install sequelize-cli globally
        run: |
          npm install -g sequelize-cli

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && echo "PostgreSQL is ready" && exit 0
            echo "Waiting for PostgreSQL..."
            sleep 3
          done
          echo "PostgreSQL failed to start" && exit 1

      - name: Check DB connection and tables
        run: |
          cd backend_bd
          echo "Checking database connection and tables..."
          node -e "
            const { Sequelize } = require('sequelize');
            const sequelize = new Sequelize({
              host: 'localhost',
              port: 5432,
              dialect: 'postgres',
              username: 'postgres',
              password: 'root',
              database: 'CarDealership_test'
            });
            sequelize.authenticate()
              .then(() => console.log('Connection established successfully.'))
              .catch(err => console.error('Unable to connect to the database:', err));
            sequelize.query('SELECT table_name FROM information_schema.tables WHERE table_schema=\'public\'')
              .then(result => {
                console.log('Tables in the database:', result[0]);
              });
          "
        env:
          DB_USER: postgres
          DB_PASSWORD: root
          DB_NAME: CarDealership_test
          DB_HOST: localhost
          DB_PORT: 5432

      - name: Setup test database (if migrations exist)
        run: |
          cd backend_bd
          npx sequelize-cli db:migrate --env test
        env:
          NODE_ENV: test
          DB_USER: postgres
          DB_PASSWORD: root
          DB_NAME: CarDealership_test
          DB_HOST: localhost
          DB_PORT: 5432

      - name: Run API tests
        run: |
          cd backend_bd
          npm test
        env:
          NODE_ENV: test
          DB_USER: postgres
          DB_PASSWORD: root
          DB_NAME: CarDealership_test
          DB_HOST: localhost
          DB_PORT: 5432
